# Generated by Django 4.2.5 on 2023-12-05 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookProfile', '0002_auto_20231124_0231'),
    ]

    operations = [
    ]
