# Generated by Django 4.2.6 on 2023-11-23 17:54

from django.db import migrations

def update_review_names(apps, schema_editor):
    Review = apps.get_model('bookProfile', 'Review')
    for review in Review.objects.all():
        review.name = review.user.username
        review.save()
    
class Migration(migrations.Migration):

    dependencies = [
        ('bookProfile', '0002_auto_20231124_0054'),
    ]

    operations = [
        migrations.RunPython(update_review_names),
    ]
