# Generated by Django 4.2.6 on 2023-10-27 05:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookProfile', '0003_auto_20231027_1117'),
    ]

    operations = [
    ]
