# Generated by Django 4.2.6 on 2023-10-29 04:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookProfile', '0005_rename_isbn_book_isbn_remove_review_created_at_and_more'),
        ('bookProfile', '0006_review_book'),
    ]

    operations = [
    ]