# Generated by Django 4.2.6 on 2023-10-29 04:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookProfile', '0007_merge_0005_rename_isbn_book_isbn_0006_review_book'),
    ]

    operations = [
    ]
