# Generated by Django 4.2.6 on 2023-10-29 08:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookProfile', '0009_review_date_review_user'),
    ]

    operations = [
    ]
