# Generated by Django 4.2.6 on 2023-11-22 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookProfile', '0003_auto_20231027_1117'),
        ('bookProfile', '0012_auto_20231029_1607'),
    ]

    operations = [
    ]
