# Generated by Django 4.2.6 on 2023-11-23 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookProfile', '0002_book'),
        ('bookProfile', '0012_auto_20231029_1607'),
    ]

    operations = [
    ]
