# Generated by Django 4.2.6 on 2023-11-23 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookProfile', '0012_auto_20231029_1607'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='isbn',
        ),
        migrations.AddField(
            model_name='book',
            name='ISBN',
            field=models.CharField(blank=True, max_length=13, null=True),
        ),
    ]
