# Generated by Django 4.2.6 on 2023-11-23 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookProfile', '0013_merge_0002_book_0012_auto_20231029_1607'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='isbn',
        ),
    ]
