# Generated by Django 4.2.6 on 2023-11-23 05:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookProfile', '0014_rename_isbn_book_isbn'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='isbn',
            new_name='ISBN',
        ),
    ]
