# Generated by Django 4.2.6 on 2023-11-23 04:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pengguna',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True, max_length=500)),
                ('booksHistory', models.ManyToManyField(blank=True, related_name='books_history', to='bookProfile.Book')),
                ('borrowedBooks', models.ManyToManyField(blank=True, related_name='borrowed_book', to='bookProfile.Book')),
                ('favoriteBooks', models.ManyToManyField(blank=True, related_name='favorite_books', to='bookProfile.Book')),
                ('reviewsHistory', models.ManyToManyField(blank=True, related_name='reviews_history', to='bookProfile.review')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
