# Generated by Django 4.2.6 on 2023-10-29 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookProfile', '0012_auto_20231029_1607'),
        ('userProfile', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pengguna',
            name='borrowedBooks',
            field=models.ManyToManyField(blank=True, related_name='borrowed_book', to='bookProfile.book'),
        ),
        migrations.AlterField(
            model_name='pengguna',
            name='booksHistory',
            field=models.ManyToManyField(blank=True, related_name='books_history', to='bookProfile.book'),
        ),
        migrations.AlterField(
            model_name='pengguna',
            name='favoriteBooks',
            field=models.ManyToManyField(blank=True, related_name='favorite_books', to='bookProfile.book'),
        ),
        migrations.AlterField(
            model_name='pengguna',
            name='reviewsHistory',
            field=models.ManyToManyField(blank=True, related_name='reviews_history', to='bookProfile.review'),
        ),
    ]
