# Generated by Django 4.2.5 on 2023-11-28 09:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bookProfile', '0002_auto_20231124_0231'),
        ('userProfile', '0002_remove_pengguna_bookshistory_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pengguna',
            name='booksHistory',
        ),
        migrations.RemoveField(
            model_name='pengguna',
            name='borrowedBooks',
        ),
        migrations.RemoveField(
            model_name='pengguna',
            name='favoriteBooks',
        ),
        migrations.RemoveField(
            model_name='pengguna',
            name='reviewsHistory',
        ),
        migrations.AlterField(
            model_name='pengguna',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='UserReviews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reviewsHistory', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviews_history', to='bookProfile.review')),
            ],
        ),
        migrations.CreateModel(
            name='UserHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booksHistory', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='books_history', to='bookProfile.book')),
            ],
        ),
        migrations.CreateModel(
            name='UserFav',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('favoriteBooks', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='favorite_books', to='bookProfile.book')),
            ],
        ),
        migrations.CreateModel(
            name='UserBorrowed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('borrowedBooks', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='borrowed_books', to='bookProfile.book')),
            ],
        ),
    ]
