# Generated by Django 4.2.5 on 2023-12-02 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userProfile', '0004_userborrowed_user_userfav_user_userhistory_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userborrowed',
            name='book_title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='userborrowed',
            name='image_url_l',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userborrowed',
            name='reference_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
