# Generated by Django 4.2.5 on 2023-12-02 14:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookProfile', '0002_auto_20231124_0231'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('userProfile', '0007_remove_userhistory_bookshistory_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_title', models.CharField(blank=True, max_length=255, null=True)),
                ('image_url_l', models.URLField(blank=True, null=True)),
                ('reference_id', models.IntegerField(blank=True, null=True)),
                ('booksHistory', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='books_history', to='bookProfile.book')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
