# Generated by Django 4.2.5 on 2023-12-02 14:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookProfile', '0002_auto_20231124_0231'),
        ('userProfile', '0008_userhistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='userhistory',
            name='book',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bookProfile.book'),
        ),
    ]
