# Generated by Django 4.2.5 on 2023-12-02 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userProfile', '0010_userhistory_is_returned'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userhistory',
            name='is_returned',
        ),
    ]
