# Generated by Django 4.2.5 on 2023-12-02 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userProfile', '0011_remove_userhistory_is_returned'),
    ]

    operations = [
        migrations.AddField(
            model_name='userhistory',
            name='is_returned',
            field=models.BooleanField(default=True),
        ),
    ]
