# Generated by Django 4.2.5 on 2023-12-06 07:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userProfile', '0014_userfav_book'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Pengguna',
        ),
    ]
