# Generated by Django 4.2.5 on 2023-12-08 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userProfile', '0016_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
