# Generated by Django 4.2.5 on 2023-12-08 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userProfile', '0018_profiledetails'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profiledetails',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='Profile_picture/'),
        ),
    ]
