# Generated by Django 4.2.5 on 2023-12-08 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userProfile', '0020_alter_profiledetails_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profiledetails',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='Profile_picture/'),
        ),
    ]
