# Generated by Django 4.2.6 on 2023-10-29 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('borrowreturn', '0003_borrowing_book_title_borrowing_image_url_l'),
    ]

    operations = [
        migrations.AddField(
            model_name='borrowing',
            name='real_return_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
