# Generated by Django 4.2.6 on 2023-10-29 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('borrowreturn', '0004_borrowing_real_return_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='borrowing',
            name='reference_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
