# Generated by Django 4.2.6 on 2023-10-29 05:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('daftar_buku', '0002_alter_main_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='main',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
