# Generated by Django 4.2.6 on 2023-10-29 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('daftar_buku', '0003_alter_main_date'),
        ('daftar_buku', '0004_feedback'),
    ]

    operations = [
    ]
