# Generated by Django 4.2.6 on 2023-10-29 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('daftar_buku', '0005_merge_0003_alter_main_date_0004_feedback'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='main',
            name='date',
        ),
    ]
